// Generated by tools/gen-fixtures — do not edit.
//
// Which data bits the sweeps actually pinned down. A zero in H4_BITS can mean
// two very different things — a contribution that is genuinely nil, or one the
// data never separated — and only this tells them apart. Bit k of byte i is
// determined when H4_KNOWN[i] has bit k set.
pub const H4_KNOWN: [u8; 20] = [
    0b00100000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b00000000, 0b11111111,
    0b01010111, 0b00000000, 0b00000000, 0b11111111, 0b11111111, 0b11111111, 0b11111111, 0b11111111,
    0b11111110, 0b11111111, 0b11111111, 0b11111111,
];
