// Generated by gen-fixtures.mjs in the scanmatik-bench repository — do not edit.
//
// Contribution of each data bit to h4, index byte * 8 + bit. Same numbers as
// core/src/h4_table.rs, written from the same calculation so the two cannot
// drift apart. See H4.kt for what they are and why they are not fitted.
package com.varuna.opendash.protocol

internal object H4Table {
    val BITS: IntArray = intArrayOf(
        0xea4065bc.toInt(), 0xe640cde1.toInt(), 0xfe419d5b.toInt(), 0xce433c2f.toInt(), 0xae467ec7.toInt(), 0x6e4cfb17.toInt(), 0xdc99f62e.toInt(), 0x8bf3eac5.toInt(),
        0x2527d313.toInt(), 0x4a4fa626.toInt(), 0x949f4c4c.toInt(), 0x1bfe9e01.toInt(), 0x37fd3c02.toInt(), 0x6ffa7804.toInt(), 0xdff4f008.toInt(), 0x8d29e689.toInt(),
        0x2893cb8b.toInt(), 0x51279716.toInt(), 0xa24f2e2c.toInt(), 0x765e5ac1.toInt(), 0xecbcb582.toInt(), 0xebb96d9d.toInt(), 0xe5b2dda3.toInt(), 0xf9a5bddf.toInt(),
        0xc18b7d27.toInt(), 0xb1d6fcd7.toInt(), 0x516dff37.toInt(), 0xa2dbfe6e.toInt(), 0x7777fa45.toInt(), 0xeeeff48a.toInt(), 0xef1fef8d.toInt(), 0xecffd983.toInt(),
        0xeb3fb59f.toInt(), 0xe4bf6da7.toInt(), 0xfbbeddd7.toInt(), 0xc5bdbd37.toInt(), 0xb9bb7cf7.toInt(), 0x41b6ff77.toInt(), 0x836dfeee.toInt(), 0x341bfb45.toInt(),
        0x6837f68a.toInt(), 0xd06fed14.toInt(), 0x921fdcb1.toInt(), 0x16ffbffb.toInt(), 0x2dff7ff6.toInt(), 0x5bfeffec.toInt(), 0xb7fdffd8.toInt(), 0x5d3bf929.toInt(),
        0xba77f252.toInt(), 0x462fe23d.toInt(), 0x8c5fc47a.toInt(), 0x2a7f8e6d.toInt(), 0x54ff1cda.toInt(), 0xa9fe39b4.toInt(), 0x613c75f1.toInt(), 0xc278ebe2.toInt(),
        0xb631d15d.toInt(), 0x5ea3a423.toInt(), 0xbd474846.toInt(), 0x484e9615.toInt(), 0x909d2c2a.toInt(), 0x13fa5ecd.toInt(), 0x27f4bd9a.toInt(), 0x4fe97b34.toInt(),
        0x9fd2f668.toInt(), 0x0d65ea49.toInt(), 0x1acbd492.toInt(), 0x3597a924.toInt(), 0x6b2f5248.toInt(), 0xd65ea490.toInt(), 0x9e7d4fb9.toInt(), 0x0e3a99eb.toInt(),
        0x1c7533d6.toInt(), 0x38ea67ac.toInt(), 0x71d4cf58.toInt(), 0xe3a99eb0.toInt(), 0xf5933bf9.toInt(), 0xd9e6716b.toInt(), 0x810ce44f.toInt(), 0x30d9ce07.toInt(),
        0x61b39c0e.toInt(), 0xc367381c.toInt(), 0xb40e76a1.toInt(), 0x5adcebdb.toInt(), 0xb5b9d7b6.toInt(), 0x59b3a9f5.toInt(), 0xb36753ea.toInt(), 0x540ea14d.toInt(),
        0xa81d429a.toInt(), 0x62fa83ad.toInt(), 0xc5f5075a.toInt(), 0xb92a082d.toInt(), 0x409416c3.toInt(), 0x81282d86.toInt(), 0x30905d95.toInt(), 0x6120bb2a.toInt(),
        0xc2417654.toInt(), 0xb642ea31.toInt(), 0x5e45d2fb.toInt(), 0xbc8ba5f6.toInt(), 0x4bd74d75.toInt(), 0x97ae9aea.toInt(), 0x1d9d334d.toInt(), 0x3b3a669a.toInt(),
        0x7674cd34.toInt(), 0xece99a68.toInt(), 0xeb133249.toInt(), 0xe4e6620b.toInt(), 0xfb0cc28f.toInt(), 0xc4d98387.toInt(), 0xbb730197.toInt(), 0x442605b7.toInt(),
        0x884c0b6e.toInt(), 0x22581045.toInt(), 0x44b0208a.toInt(), 0x89604114.toInt(), 0x200084b1.toInt(), 0x40010962.toInt(), 0x800212c4.toInt(), 0x32c42311.toInt(),
        0x65884622.toInt(), 0xcb108c44.toInt(), 0xa4e11e11.toInt(), 0x7b023abb.toInt(), 0xf6047576.toInt(), 0xdec8ec75.toInt(), 0x8f51de73.toInt(), 0x2c63ba7f.toInt(),
        0x58c774fe.toInt(), 0xb18ee9fc.toInt(), 0x51ddd561.toInt(), 0xa3bbaac2.toInt(), 0x75b7531d.toInt(), 0xeb6ea63a.toInt(), 0xe41d4aed.toInt(), 0xfafa9343.toInt(),
        0xc735201f.toInt(), 0xbcaa46a7.toInt(), 0x4b948bd7.toInt(), 0x972917ae.toInt(), 0x1c9229c5.toInt(), 0x3924538a.toInt(), 0x7248a714.toInt(), 0xe4914e28.toInt(),
        0xfbe29ac9.toInt(), 0xc505330b.toInt(), 0xb8ca608f.toInt(), 0x4354c787.toInt(), 0x86a98f0e.toInt(), 0x3f931885.toInt(), 0x7f26310a.toInt(), 0xfe4c6214.toInt(),
        0xce58c2b1.toInt(), 0xae7183fb.toInt(), 0x6e23016f.toInt(), 0xdc4602de.toInt(), 0x8a4c0325.toInt(), 0x265800d3.toInt(), 0x4cb001a6.toInt(), 0x9960034c.toInt(),
    )
}
